version: "3.8"

services:
  node:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: ["npm", "run", "dev"]

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: alisandro
      POSTGRES_PASSWORD: alisandro
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
